version: '3.0'
services:

  mariadb:
    container_name: rabbitmq
    image: rabbitmq:3.8.2-management-alpine
    hostname: rabbitmq
    ports:
      - 15672:15672
      - 5672:5672
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
    restart: always
