version: '3.0'
services:

  crm:
    container_name: crm
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 127.0.0.1:8282:5000
    environment:
      - OPENSHIFT_MYSQL_DB_USERNAME=damucrm
      - OPENSHIFT_MYSQL_DB_PASSWORD=jkdfssd766776gxA!
      - OPENSHIFT_MYSQL_DB_HOST=172.17.0.1
      - OPENSHIFT_MYSQL_DB_PORT=3306
      - OPENSHIFT_GO_IP=0.0.0.0
      - OPENSHIFT_GO_PORT=5000
      - OPENSHIFT_APP_NAME=damucrm
    restart: always
    logging:
      options:
        max-size: 1m
