FROM golang:1.14.2-alpine AS builder

#RUN apk add --no-cache git pkgconfig libxml2-dev zip libreoffice build-base

#WORKDIR /tmp/gobuild

#COPY ./golang/go.mod .
#COPY ./golang/go.sum .

#RUN go mod download

#COPY ./golang .

#Test stage
#RUN CGO_ENABLED=1 GOOS=linux GOPATH=/gobuild

#Build stage
#RUN go build -o  ./out/app .


#FROM ubuntu:18.04

#RUN apt-get update \
# && apt-get install -y libxml2-dev zip libreoffice\
# && apt-get autoremove -y \
# && mkdir -p /opt/crm

#COPY ./crm/static /opt/crm/static
#COPY ./crm/uploads /opt/crm/uploads
#COPY  --from=builder /tmp/gobuild/out/app /opt/crm/app

#WORKDIR /opt/crm

#RUN chmod +x ./app

#CMD ["./app"]
