apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- ingress.yaml
- service.yaml
commonLabels:
  app_env: dev
#  app_name: 
  org: onetech
  project: forte-
images:
- name: 227185325630.dkr.ecr.eu-west-1.amazonaws.com/
  newTag: 