apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crm
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'git@git.dar.kz:crediton-3/crm-mfo-local.git'
    path: deploy/app
    targetRevision: argo
    helm:
      valueFiles:
        - values_dev.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: develop
  syncPolicy:
    automated: {}
    syncOptions:     
      - CreateNamespace=true 