image: docker:18.09


before_script:
    -  apk add --no-cache python3 py3-pip 
    -  pip3 install --upgrade pip 
    -  pip3 install awscli
    -  export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
    -  export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
    -  export AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION

services:
  - docker:18.09-dind

stages:
  - build_push

build_push_:
  stage: build_push
  script:
     - echo "BUILD BASE IMAGE ${CI_COMMIT_SHA:0:8}"
     - cd app/crm/
     - aws ecr get-login-password --region eu-west-1 | docker login --username AWS --password-stdin 227185325630.dkr.ecr.eu-west-1.amazonaws.com
     - docker build -f Dockerfile -t 227185325630.dkr.ecr.eu-west-1.amazonaws.com/dar-eco/mycrm-crm:${CI_COMMIT_SHORT_SHA} .
     - docker push  227185325630.dkr.ecr.eu-west-1.amazonaws.com/dar-eco/mycrm-crm:${CI_COMMIT_SHORT_SHA}
  tags:
    - autoscaling-runner
